export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";

export const GET_USER_STEP_COUNTS_START = "GET_USER_STEP_COUNTS_START";
export const GET_USER_STEP_COUNTS_SUCCESS = "GET_USER_STEP_COUNTS_SUCCESS";
export const GET_USER_STEP_COUNTS_FAIL = "GET_USER_STEP_COUNTS_FAIL";

export const GET_USER_HEART_POINTS_START = "GET_USER_HEART_POINTS_START";
export const GET_USER_HEART_POINTS_SUCCESS = "GET_USER_HEART_POINTS_SUCCESS";
export const GET_USER_HEART_POINTS_FAIL = "GET_USER_HEART_POINTS_FAIL";

export const GET_USER_CALORIES_BURNT_START = "GET_USER_CALORIES_BURNT_START";
export const GET_USER_CALORIES_BURNT_SUCCESS =
  "GET_USER_CALORIES_BURNT_SUCCESS";
export const GET_USER_CALORIES_BURNT_FAIL = "GET_USER_CALORIES_BURNT_FAIL";

export const UPDATE_USER_SCORE_START = "UPDATE_USER_SCORE_START";
export const UPDATE_USER_SCORE_SUCCESS = "UPDATE_USER_SCORE_SUCCESS";
export const UPDATE_USER_SCORE_FAIL = "UPDATE_USER_SCORE_FAIL";

export const GET_SELECTED_USER_START = "GET_SELECTED_USER_START";
export const GET_SELECTED_USER_SUCCESS = "GET_SELECTED_USER_SUCCESS";
export const GET_SELECTED_USER_FAIL = "GET_SELECTED_USER_FAIL";

export const GET_LEADERBOARD_DATA_START = "GET_LEADERBOARD_DATA_START";
export const GET_LEADERBOARD_DATA_SUCCESS = "GET_LEADERBOARD_DATA_SUCCESS";
export const GET_LEADERBOARD_DATA_FAIL = "GET_LEADERBOARD_DATA_FAIL";
